name: Eleventy build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Builder
        uses: TartanLlama/actions-eleventy@master
      - run: cp -r static/* _site/static/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          github_token: ${{ secrets.GITHUB_TOKEN }}s