name: Eleventy build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Builder
        uses: fritzvd/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: cheesesofmexico.com
